//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace faculty
{
    using System;
    using System.Collections.Generic;
    
    public partial class studint
    {
        public int id { get; set; }
        public string name { get; set; }
        public string adress { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<int> deb_id { get; set; }
    
        public virtual debartments debartments { get; set; }
    }
}
